---
title: "6103_k_vals"
author: "bml72"
date: "4/27/2020"
output:
  html_document:
    code_folding: hide
    number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, results = 'hide', message = F)

knitr::opts_knit$set(root.dir = './imputed_files')

options(scientific=T, digits = 3) 
```

```{r basic, include=F}
# use this function to conveniently load libraries and work smoothly with knitting
# can add quietly=T option to the require() function
loadPkg = function(pkg, character.only = FALSE) { 
  if (!character.only) { pkg <- as.character(substitute(pkg)) }
  pkg <- ifelse(!character.only, as.character(substitute(pkg)) , pkg)  
  if (!require(pkg,character.only=T, quietly =T)) {  install.packages(substitute(pkg),dep=T); if(!require(pkg,character.only=T)) stop("Package not found") } 
}
loadPkg(knitr)

# unload/detact package when done using it
unloadPkg = function(pkg, character.only = FALSE) { 
  if(!character.only) { pkg <- as.character(substitute(pkg)) } 
  search_item <- paste("package", pkg,sep = ":") 
  while(search_item %in% search()) { detach(search_item, unload = TRUE, character.only = TRUE) } 
}
```

```{r loading, include = T}
measles = read.csv('measles_imputed.csv')

measles <- measles[-c(1, 3:6)]

str(measles)
```

```{r knn, include = T}
loadPkg('FNN')

# Scaling numerical features
scaled_measles <- as.data.frame(scale(measles[2:7], center = TRUE, scale = TRUE))

set.seed(1000)

measles_sample <- sample(2, nrow(scaled_measles), replace=TRUE, prob=c(0.67, 0.33))

measles_training <- scaled_measles[measles_sample==1, 1:6]
measles_test <- scaled_measles[measles_sample==2, 1:6]

measles.trainLabels <- measles[measles_sample==1, 1]
measles.testLabels <- measles[measles_sample==2, 1]

measles_pred <- knn(train = measles_training, test = measles_test, cl=measles.trainLabels, k=3)
```

```{r}
chooseK = function(k, train_set, val_set, train_class, val_class){
  
  # Build knn with k neighbors considered.
  set.seed(1)
  class_knn = knn(train = train_set,    #<- training set cases
                  test = val_set,       #<- test set cases
                  cl = train_class,     #<- category for classification
                  k = k) #,                #<- number of neighbors considered
                  # use.all = TRUE)       #<- control ties between class assignments
                                        #   If true, all distances equal to the kth 
                                        #   largest are included
  
  tab = table(class_knn, val_class)
  
  # Calculate the accuracy.
  accu = sum(tab[row(tab) == col(tab)]) / sum(tab)                         
  cbind(k = k, accuracy = accu)
}

# The sapply() function plugs in several values into our chooseK function.
# function(x)[function] allows you to apply a series of numbers
# to a function without running a for() loop.
knn_different_k = sapply(seq(1, 21, by = 2),  #<- set k to be odd number from 1 to 21
                         function(x) chooseK(x, 
                                             train_set = measles_training,
                                             val_set = measles_test,
                                             train_class = measles.trainLabels,
                                             val_class = measles.testLabels))

# Reformat the results to graph the results.
str(knn_different_k)
knn_different_k = data.frame(k = knn_different_k[1,],
                             accuracy = knn_different_k[2,])

# Plot accuracy vs. k.
# install.packages("ggplot2")
loadPkg(ggplot2)

ggplot(knn_different_k,
       aes(x = k, y = accuracy)) +
  geom_line(color = "orange", size = 1.5) +
  geom_point(size = 3)

```